### ISSUE TITLE
Auto Update Does Not Work

### ISSUE THREAD

**Issue by RobbaYaga** [pwatson100/alienrpg#134]
The subject line says it all. As a non-coder, GitHub is a nightmare to try and find the last update. Please arrange to have the auto update work correctly. I nearly lost a game session with the last update that did not auto activate due to character sheets not opening.

Thanks.

**Comment by pwatson100** [comment]
You really need to provide more information than just saying it does not work.  I have had no other reports of people having issues updating. Since the last release there have been 290 downloads.  
What version O/S are you using? 
What version of the system are you currently on?
Are you using the Foundry system update feature, if so do you get an error and what is it?
