### ISSUE TITLE
Dice rolls not working on new world

### ISSUE THREAD

**Issue by gerdos** [pwatson100/alienrpg#15]
I am opening this issue upon the closed pull request, as I was unable to find you on Foundry Discord and there does not seems to be a dedicated Alien group there. 

I was able to replicate the bug that stops the dice rolls from working: 

When creating a new word, I create a new actor, and I can roll just fine (BTW the tables you mentioned are still not there). I opened up the "Stunt-Skills" compendium and drag and drop "Close Combat" onto the Skills sheet.

After this the bug happens, and I am not able to roll anything with the error message:

```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at actor.js:38
    at Array.reduce (<anonymous>)
    at alienrpgActor.getRollData (actor.js:34)
    at alienrpgActor.rollAbility (actor.js:285)
    at alienrpgActorSheet._onRoll (actor-sheet.js:365)
    at HTMLHeadingElement.dispatch (jquery.min.js:2)
    at HTMLHeadingElement.v.handle (jquery.min.js:2)
```

Foundy: 0.7.7
Alien 1.2.12

**Comment by pwatson100** [comment]
I have corrected the bug with the Skill-Stunts pop up which was not displaying properly.  
As we found the errors were because the Skill-Stunts are not Items in the normal term but just there to enable users to add any desired stunt text (from the book) which is displayed when the player clicks on the spanners.   As we discovered dragging these on to the Actor corrupts the data.  
One way to prevent this is to set the user permissions of the Skill-Stunts folder to "All Players" None.  
This will still allow the pop up to appear but will prevent players from dragging the skills on to their Actor as the folder will not be visible to them.

**Comment by pwatson100** [comment]
I have corrected the bug with the Skill-Stunts pop up which was not displaying properly.  
As we found the errors were because the Skill-Stunts are not Items in the normal term but just there to enable users to add any desired stunt text (from the book) which is displayed when the player clicks on the spanners.   As we discovered dragging these on to the Actor corrupts the data.  
One way to prevent this is to set the user permissions of the Skill-Stunts folder to "All Players" None.  
This will still allow the pop up to appear but will prevent players from dragging the skills on to their Actor as the folder will not be visible to them.
