### ISSUE TITLE
Enhancement Request - Fake Air or other supply rolls for Synthetics

### ISSUE THREAD

**Issue by SoundSherpa** [pwatson100/alienrpg#247]
If someone is playing an android it can be a little awkward when everyone has to make an air supply roll except them. You can manually have them roll stress dice but it would be cool to fake this on the synthetic sheet to never roll a 1 on those supply checks.

**Comment by pwatson100** [comment]
Good Idea.  I have changed the system so when the Human Panic box is checked Conditions and Consumables are displayed and work as normal.   I will do actual rolls rather than fake ones as the PC should be simulating using the resources over time e.g., they will leak some oxygen just in case anyone looks at their meter etc. 
Will be in the next release.
