### ISSUE TITLE
Question - How to drag Weapon or Skill rolls to the Macro bar?

### ISSUE THREAD

**Issue by Sonny-Crockett** [pwatson100/alienrpg#35]
Great work, we have been running Destroyer of Worlds and this system has been great with all the different components going on at the same time. 

There reason I would like a Macro Bar action is so I can easily add a sound file effect to play during weapon rolls. 

If its just easier to give me the syntax to make my own macro for Skills or Weapons, that works just as good. 

Thanks again!

**Comment by pwatson100** [comment]
Thank you.  So currently you can drag weapons on to the macro bar and click on them to roll as long as the token is selected.  Skills are fixed in the sheet so can't be dragged but I believe the are accessible in macros using the @ notation.  I will check and let you know. I have done some work on setting up Alien for Token Action HUD which makes those sort of rolls a lot easier so I will pick that up again.

**Comment by pwatson100** [comment]
I double checked and the @ notation does work.  
For Attributes: 
@str, @agl, @wit & @emp do the trick.  

For skills:
@skills.heavyMach.value
@skills.closeCbt.value
@skills.stamina.value
@skills.rangedCbt.value
@skills.mobility.value
@skills.piloting.value
@skills.command.value
@skills.manipulation.value
@skills.medicalAid.value
@skills.observation.value
@skills.survival.value
@skills.comtech.value

Hope this helps you with the macros.

**Comment by Sonny-Crockett** [comment]
Thanks so much for that! Pulse rifle SFX will be epic!
