### ISSUE TITLE
Add a system setting to make all GM rolls public.

### ISSUE THREAD

**Issue by pwatson100** [pwatson100/alienrpg#46]
Some GM's don't want their rolls to be hidden from the players so implement a system setting and create logic to make all GM rolls (within my control) public.

**Comment by David-Zvekic** [comment]
If you want GM xeno rolls to obey the visibility settings in the chat bar then look at my latest pull request and comment out line 807 in actor.js to make it into  // whisper: game.users.entities.filter((u) => u.isGM).map((u) => u._id),

since this note is going to become obsolete if I update my branch I'll put the change into my branch and make a commit version of it.

**Comment by pwatson100** [comment]
Thank you for doing this. :)
