### ISSUE TITLE
Alien RPG - Chariots of the Gods : Improvements and QoL suggestions

### ISSUE THREAD

**Issue by GittaNaba2021** [pwatson100/alienrpg#55]
Hello,

As I'm running the scenario on Foundry VTT, here is a list of possible improvements (which could be added to other modules for some of them):
- Add a Size property for Creatures and Vehicules inside their sheet. Small creatures get a bonus to defense, larger ones a malus, so it's important to track this setting as GM as it impacts gameplay.
- Add a Personnality property to PC and NPC sheet to make it easier to notice (players do not expect it inside "Appearance" text box). This property is used in every Cinematic plays.
- Remove the "Personal Agenda" Item from "Skills" tab and move it "General" tab. Players expect to have it there, not inside "Skills" tab. However the "Personal Agenda" item from "Skills" allows for drag'n'drop from Compedium which is easier to manage for the GM.
- The new typo makes blocs of text harder to read due to letters' cropping. It is also to very hard to make the difference between 5 and 6 - both numbers look almost exactly the same.
- Add a picture of Bloodburster inside "Players Handouts", as it is a part of a very important scene.
- Add a portrait of other NPC inside "Player Handouts". Currently it is not possible to show players what they look like without spoiling their character sheet.
- Add damage type to Weapons : armor-piercing, single-shot, armor doubled, fire, blast, to make it easier to track by GM and players. 
- Add a new condition : "Burning" to PC, NPC and Creatures, with an automated system to roll damage as long as the victim is burning following the rules.
- Create a button to roll critical injuries directly from the corresponding sheet (PC/NPC/Creature).
- Manage power on an individual item level, to support PC with multiple items relying on power.

Thanks for listening !

**Comment by pwatson100** [comment]
Thank you for the suggestions:  

_Add a Size property for Creatures and Vehicles inside their sheet. Small creatures get a bonus to defense, larger ones a malus, so it's important to track this setting as GM as it impacts gameplay._
I have added this as an enhancement as I agree with you.  I am not sure it's needed for Vehicles as they are always large targets.   The stat blocks for creatures in the rules do not offer any size numbers which is why it's not there.   

_Add a Personnality property to PC and NPC sheet to make it easier to notice (players do not expect it inside "Appearance" text box). This property is used in every Cinematic plays._
That is what the Notes tab is for.  Looking at the "Official" character sheet this is not catered for.  Perhaps I should change the name of the Notes tab to Appearance? 

_Remove the "Personal Agenda" Item from "Skills" tab and move it "General" tab. Players expect to have it there, not inside "Skills" tab. However the "Personal Agenda" item from "Skills" allows for drag'n'drop from Compedium which is easier to manage for the GM._

I want to make a distinction between a players "Personal Agenda" and one that is a "Directed Agenda" thrust on them by the GM or scenario.  A personal agenda is something that lives with the PC across a number of scenarios (if the  survive).  The panel on the Skills tab is just for Agenda and Story cards as I explain in the MO/TH/ER instructions which would be deleted at the end of the scene or scenario  

_The new typo makes blocs of text harder to read due to letters' cropping. It is also to very hard to make the difference between 5 and 6 - both numbers look almost exactly the same._
That is why I put in the ability to change the fonts to something the user prefers.  

_Add a picture of Bloodburster inside "Players Handouts", as it is a part of a very important scene._
I thought I had included that image in the "Art of Alien" section.  I will include it in the next patch but I am not sure if/when that will be released.

_Add a portrait of other NPC inside "Player Handouts". Currently it is not possible to show players what they look like without spoiling their character sheet._
Time constraints prevented a few things that would have been nice to be added to the modules and this is one of them. It will not be addressed in future patches.  For DoW it does way that the players get the AWOL marines character sheets so that journal entry can be shared with the players.  For the other scenarios/NPC/Creatures right clicking on the actor in the sidebar will give an option to "View Character Artwork" which can then be shared with the players.  Alternately all of the artwork is available so you could create your own journal images.  You will find them in modules/alienrpg-_MODULENAME_/images/avatar   

_Add damage type to Weapons : armor-piercing, single-shot, armor doubled, fire, blast, to make it easier to track by GM and players._
I like the idea,  The only issue is some weapons give multiple (Armor piercing, full auto) that can't be implemented using a dropdown so I am not quite sure how it would be implemented.  
I have added this as an enhancement to the project.

_Add a new condition : "Burning" to PC, NPC and Creatures, with an automated system to roll damage as long as the victim is burning following the rules._
Nice idea.  Currently the system does not support any conditions but I might be able to implement something using Active Effects.  I have not looked with these yet.  I have added this as an enhancement to the project.

_Create a button to roll critical injuries directly from the corresponding sheet (PC/NPC/Creature)._
I have added this as an enhancement to the project.

_Manage power on an individual item level, to support PC with multiple items relying on power._
I have reworked how Power supply rolls are done and it will be in the next system release.


All good feedback thank you again.  

Just to be clear for the Free League modules I am only fixing bugs and have no control over the release of any patches so it's unlikely a patch will be released (by FL) for a missing image even if I supply it.  

Additionally with the release of the modules (which is good) I have to be careful when I release any updates to the system (which is fully under my control) that they do not break or cause inaccuracies in content of the modules.  For instance adding the size field to the creatures would cause a default size to be added to the creatures in the modules.  There would be an expectation from people who have purchased the modules that these would be correct and I would have updated all the creatures.  That would not be the case as my agreement with FL is for bug fixes only.
