### ISSUE TITLE
EMP / WITS skills are mislabeled.

### ISSUE THREAD

**Issue by SeriouslyMoe** [pwatson100/alienrpg#6]
![2020-08-06 20_55_08-Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application - Vivaldi](https://user-images.githubusercontent.com/10166760/89597105-2a1ba380-d827-11ea-851e-0a8796e298fc.png)

The empathy skills and wits skills have been swapped on the character sheet from what I've experienced. I haven't delved into everything, but this is the only occurrence I've for sure found it in.

**Comment by SeriouslyMoe** [comment]
Did some testing, it's not just a visual error, rolling the skills through the sheet is also bugged and results in empathetic observation rolls and wits medical aid rolls.

**Comment by pwatson100** [comment]
Thanks for spotting this.  It's a regression error.  I have a fix in place but am working on the migration script so all existing characters are updated.    I will get a release out ASAP.

**Comment by superseva** [comment]
after running  1.0.9 update the existing actors still have EMP / WITS skills mixed. The new actors created seam to have popper skill-attribute connections. Can we try and force migration script to run again on existing actors ?

**Comment by pwatson100** [comment]
That is really odd.  Did the blue migration banners show when you opened the world?    I did some tests on my other system and the migration seemed to work OK and changed the emp and wit skills.     
You can force it to do another migration by opening the world then F12 to get the console and putting this: 
game.settings.set('alienrpg', 'systemMigrationVersion', "1.0.8");

Then close the FVTT and then in C:\Users\YOURNAME\AppData\Local\FoundryVTT\Data\worlds\alienrelease
edit 
world.json
find   "systemVersion": "1.0.8",
and change it to  "systemVersion": "1.0.9",
and save. 

Then restart FVTT and launch your world. 
I will do some more tests tomorrow (In the UK so it's getting late).
Can you ping me on Discord and let me know how you get on please.

**Comment by SwanVestas** [comment]
1.0.9 update works fine for me (EMP and WIT skills are correct). Great job on this - helped to convince me to move my Alien game from FG to Foundry :)

**Comment by pwatson100** [comment]
Found a few issues with the character (emp/wit attributes & mod's not being recalculated) migration which have now been corrected.

**Comment by pwatson100** [comment]
Found a few issues with the character (emp/wit attributes & mod's not being recalculated) migration which have now been corrected.

**Comment by SwanVestas** [comment]
Hi.

 

Great, thanks for the update. I’m loving this module for Foundry.

 

I have a query regarding panic. Not sure if this is the correct place to mention it or whether I raise a Github issue (all a bit new to me!) or whether I should just manually track a condition to deal with it.

 

Is it possible to add a panic status button to an actor so that when you next roll on the panic table it takes either your existing value, the new roll (if higher) or just adds one if lower (as panic should always raise).

 

At the moment, you can click the stress button on the actor sheet to roll for stress (which can indicate panic if you roll high enough) but any future rolls only take into account the stress value + the 1d6 roll and not any current level of panic on the actor.

 

Cheers.

 

Steve.

**Comment by pwatson100** [comment]
Hi Steve,
  Thanks for the feedback and I am glad your making use of the system.  
I get what your saying.  It's a bit tricky as some of the panic rolls only last one turn and/or also effect any players around the PC.  

Currently, Right Clicking on Stress allows the player to add or subtract stress dice on a single roll.

I could put the result of the panic roll in a box on the PC's sheet.  
The problem is working out the end of the turn, as not all stress happens in combat, additionally many effects only last one turn.  I would also need to interact with the combat tracker which is a little beyond my current knowledge.  

When I put the system together I expected this to be managed manually (perhaps using status icons on the token, manually increasing Stress or using the critical injuries box to record the effect) but I do see how it would make things easier.  

All said I think it's worth at least adding a Panic check box on the sheet to at least let the player record they have a panic condition while I think about how this could be done.   

Regards,
   Paul..

**Comment by SwanVestas** [comment]
Hi Paul,

 

Thanks for the response – yes, sorry I didn’t think it would be easy 😊

 

I guess a Panic check box on the actor sheet would be handy just to visually check if a player is already panicking when they make a new panic roll (maybe in the conditions area – see pic?). Or I could just use a token status symbol to be fair and note the panic text into the Critical Injuries box as you suggest. You make a good point about out of stress combat and end of turns.

 



 

The More Panic rule on P104 of the rulebook is what I was originally thinking of where if you are already suffering a panic effect (having already rolled a 7+ on the table) and are forced to make a new panic roll (and happen to roll a lower number inc new stress value), then your panic total just goes up one level on the panic table to the next horrible effect.

 

Anyway, Alien is a great game and I have enjoyed moving all my content from FG to Foundry (animated scenes etc makes it mucho fun!) & I look forward to any updates that you bring to your module.

 

Cheers,

 

Steve.

**Comment by SwanVestas** [comment]
Hi Paul,

 

Sorry the pic didn’t show up – you captured it perfectly though in your update .. although you have spelt Panicked wrong on the sheet (left the K off!) 😊

 

Love the flashing red though!

 

Not too sure on Discord … I couldn’t find pwatson100 on The Foundry group to DM you the image - sorry (new at Discord too haha – my user id there in the Foundry VTT group is McKnuckles#8676).

 

Cheers,

 

Steve.
