### ISSUE TITLE
Add a "Death Roll" button on PC sheets

### ISSUE THREAD

**Issue by GittaNaba2021** [pwatson100/alienrpg#80]
Hello,

It would be useful to add a "Death Roll" button (Stamina, no Push, no Stress Dice) on PC sheets.
This feature will be useful for all Alien games, and it is currently not very practical for a GM to trigger such a roll, or have PC do it themselves (as it must ignore stress). Also, clicking on a button labeled "Death Roll" adds some pressure to PC. 

Thanks for listening !

**Comment by pwatson100** [comment]
Ah OK.  Thank you for clarifying.  Once I have the 0.8.x version of the system fully tested I will see what I can do.

**Comment by NocFenix** [comment]
@GittaNaba2021, technically the user can context-click on Stamina and input the necessary modifiers to ignore stress. I'm not sure a whole new button needs to be added for this since it is basically asking to introduce something redundant that has the potential to introduce more bugs than benefits. Ultimately it is up to Paul to decide, of course.

**Comment by pwatson100** [comment]
As you suggest they can Context click on Stamina do do the roll so I won't add a button.
