### ISSUE TITLE
The power supply roll 

### ISSUE THREAD

**Issue by Sonny-Crockett** [pwatson100/alienrpg#9]
Has there been a change with the power supply roll, I have been unable to get it to work since 7.5?

Thanks !

**Comment by pwatson100** [comment]
Hi,  The supply rolls seem OK on my system.  I tested it on a fresh install.  
Is it just the Power button or all of them?  
Are there any error messages in the console (F12)?
If either could, you send me a screen shot of the console.

**Comment by Sonny-Crockett** [comment]
So my understanding is for items/equipment when we edit it, we should have a spot to add the number of power supply quantity that can be rolled against. That is what I am seeing that is missing. 

I see the one on the main sheet, but wondering how to deal with multiple items at different power supply levels?

Thanks for your help!

**Comment by pwatson100** [comment]
Ah, I am with you now.   At present, other than weapons, items don't effect any of the stats.  So the only way to record any modifiers is in the text box.   So the player has to manually updated the consumables boxes with the number. 
Not great I know.  
With Armor it was easy because there is only one thing to modify but for general equipment they can affect any one or more consumables as well as mods to attributes and skills.  
I am thinking of adding another tab to the items sheet listing all of the possible mod options, I could then use those to update consumables and stats.  

>>I see the one on the main sheet, but wondering how to deal with multiple items at different power supply levels?<<
That would be really hard for me to do as the main sheet just has a total,  I would need to store the total and track the individual items (contributing to the total) to fully automate that.    Also a player might want to take a point off of battery a then next time a point off of battery b.  

I need to look through all the items and work out the combinations of consumables etc. and see how best I can make their stats interact with the PC's.

**Comment by Sonny-Crockett** [comment]
I can see how complicated a full automation can be.  Thanks for explaining all that.

Perhaps could we just have editable number fields, generic item having all the supply fields(hide-able for ones we don't need, if thats even possible) and we can just track the stat manually but in a dedicated space until you can figure out a way to more easily connect. 

Also could one just have the generic macro for the supply rolls(on item page), and player could just be asked to record the result/net change in item number fields?

**Comment by pwatson100** [comment]
I thought about having a single generic field then look at a few items and saw they gave food and water bonuses.  
As soon as I have finished the colour change stuff I will put my (whole) mind to it.   
It's on my project to do list for the V1.2.8 release.
